export const mockWorkers = [
  {
    id: 1,
    name: 'Arjuna Mahendra',
    avatar: 'AM',
    role: 'Painter',
    category: 'Painters',
    location: 'Colombo 5',
    experience: '8 years exp.',
    experienceYears: 8,
    rating: 4.9,
    reviews: 127,
    price: 5000,
    unit: '/ room',
    distance: 4,
    verified: true,
    featured: true,
    pro: true,
    avatarClass: 'bg-emerald-700 text-white',
  },
  {
    id: 2,
    name: 'Sunil Wijesinghe',
    avatar: 'SW',
    role: 'Painter',
    category: 'Painters',
    location: 'Dehiwala',
    experience: '12 years exp.',
    experienceYears: 12,
    rating: 4.2,
    reviews: 84,
    price: 4200,
    unit: '/ room',
    distance: 8,
    verified: true,
    featured: false,
    pro: false,
    avatarClass: 'bg-slate-200 text-slate-600',
  },
  {
    id: 3,
    name: 'Kasun Perera',
    avatar: 'KP',
    role: 'Painter',
    category: 'Painters',
    location: 'Battaramulla',
    experience: '5 years exp.',
    experienceYears: 5,
    rating: 4.7,
    reviews: 210,
    price: 6500,
    unit: '/ room',
    distance: 12,
    verified: true,
    featured: false,
    pro: false,
    avatarClass: 'bg-slate-950 text-white',
  },
  {
    id: 4,
    name: 'Nimali Fernando',
    avatar: 'NF',
    role: 'Interior Designer',
    category: 'Interior Designers',
    location: 'Colombo 7',
    experience: '6 years exp.',
    experienceYears: 6,
    rating: 4.6,
    reviews: 96,
    price: 12000,
    unit: '/ project',
    distance: 6,
    verified: false,
    featured: false,
    pro: false,
    avatarClass: 'bg-purple-100 text-purple-700',
  },
  {
    id: 5,
    name: 'Ruwan Jayasinghe',
    avatar: 'RJ',
    role: 'Painter',
    category: 'Painters',
    location: 'Nugegoda',
    experience: '3 years exp.',
    experienceYears: 3,
    rating: 3.9,
    reviews: 42,
    price: 3500,
    unit: '/ room',
    distance: 18,
    verified: false,
    featured: false,
    pro: false,
    avatarClass: 'bg-orange-100 text-orange-700',
  },
  {
    id: 6,
    name: 'Shanthi Abeysekera',
    avatar: 'SA',
    role: 'Interior Designer',
    category: 'Interior Designers',
    location: 'Colombo 3',
    experience: '10 years exp.',
    experienceYears: 10,
    rating: 4.8,
    reviews: 156,
    price: 15000,
    unit: '/ project',
    distance: 3,
    verified: true,
    featured: true,
    pro: false,
    avatarClass: 'bg-blue-100 text-blue-700',
  },
];
