const translations = {
  English: {
    good_morning: "Good morning",
    find_skilled: "Find the best skilled professionals in Sri Lanka",
    explore_sub: "Browse through our wide range of services",
    search_hint: "What service do you need?",
    search_location: "Colombo, Sri Lanka",
    search: "Search",
    popular: "Popular",
    explore_categories: "Explore Categories",
    view_all: "View All Categories",
    top_rated: "Top Rated Professionals",
    book_now: "Book Now",
    view_profile: "View Profile",
    home: "Home",
    search_nav: "Search",
    bookings: "Bookings",
    verified: "Verified",
    unverified: "Unverified Worker",
    featured: "Featured",
    starting_at: "Starting at",
    rate_review: "Rate & Review",
    feedback_given: "Feedback Given",
    about: "About",
    filters: "Filters",
    refine_search: "Refine your search",
    price_range: "Price Range",
    under_5000: "Under LKR 5,000",
    between_5000_15000: "LKR 5,000 - 15,000",
    ratings: "Ratings",
    distance: "Distance",
    verified_status: "Verified Status",
    verified_only: "Verified Workers Only",
    categories: "Categories",
    clear_all_filters: "Clear All Filters",
    showing: "Showing",
    professionals: "Professionals",
    in: "in",
    no_professionals: "No professionals found",
    no_professionals_sub: "Try changing your search, filters, category, or distance.",
    sort_by: "Sort by",
    pro_member: "Pro Member",
    top_experts: "Top 5% SkilledLK Experts",
    location: "Location",
    within_5km: "Within 5km",
    within_10km: "Within 10km",
    within_20km: "Within 20km",
    any_distance: "Any distance",
    recommended: "Recommended",
    highest_rated: "Highest Rated",
    lowest_price: "Lowest Price",
    highest_price: "Highest Price",
    most_experienced: "Most Experienced",
    privacy_policy: "Privacy Policy",
    terms_of_service: "Terms of Service",
    help_center: "Help Center",
    contact_support: "Contact Support",
    notifications: "Notifications",
    mark_all_read: "Mark all as read",
    show_less_notif: "Show less notifications",
    see_all_notif: "See all notifications",
    messages: "Messages",
    profile: "Profile",
    toggle_menu: "Toggle menu",
    reviews_label: "reviews",
    starting_from: "Starting from",
    chat_first: "Chat first",
  },
  Sinhala: {
    good_morning: "සුභ උදෑසනක්",
    find_skilled: "ශ්‍රී ලංකාවේ හොඳම දක්ෂ වෘත්තිකයන් සොයා ගන්න",
    explore_sub: "අපගේ පුළුල් පරාසයක සේවාවන් ගවේෂණය කරන්න",
    search_hint: "ඔබට අවශ්‍ය සේවාව කුමක්ද?",
    search_location: "කොළඹ, ශ්‍රී ලංකාව",
    search: "සොයන්න",
    popular: "ජනප්‍රිය",
    explore_categories: "ප්‍රවර්ග ගවේෂණය කරන්න",
    view_all: "සියලුම ප්‍රවර්ග බලන්න",
    top_rated: "ඉහළම ශ්‍රේණිගත වෘත්තිකයන්",
    book_now: "දැන්ම වෙන්කරවා ගන්න",
    view_profile: "පැතිකඩ බලන්න",
    home: "මුල් පිටුව",
    search_nav: "සොයන්න",
    bookings: "වෙන්කරවා ගැනීම්",
    verified: "සත්‍යාපිතයි",
    unverified: "නොවැලැක්වූ සේවකයා",
    featured: "විශේෂිත",
    starting_at: "ආරම්භක මිල",
    rate_review: "ශ්‍රේණිගත කර සමාලෝචනය කරන්න",
    feedback_given: "ප්‍රතිපෝෂණය ලබා දී ඇත",
    about: "පිළිබඳව",
    filters: "පෙරහන්",
    refine_search: "ඔබගේ සෙවීම් පිරිපහදු කරන්න",
    price_range: "මිල පරාසය",
    under_5000: "LKR 5,000 ට අඩු",
    between_5000_15000: "LKR 5,000 - 15,000",
    ratings: "ශ්‍රේණිගත කිරීම්",
    distance: "දුර",
    verified_status: "සත්‍යාපිත තත්ත්වය",
    verified_only: "සත්‍යාපිත සේවකයින් පමණි",
    categories: "ප්‍රවර්ග",
    clear_all_filters: "සියලුම පෙරහන් ඉවත් කරන්න",
    showing: "පෙන්වමින්",
    professionals: "වෘත්තිකයන්",
    in: "තුළ",
    no_professionals: "කිසිදු වෘත්තිකයෙකු හමු නොවීය",
    no_professionals_sub: "ඔබගේ සෙවීම, පෙරහන්, ප්‍රවර්ගය හෝ දුර වෙනස් කිරීමට උත්සාහ කරන්න.",
    sort_by: "අනුපිළිවෙල",
    pro_member: "ප්‍රෝ සාමාජික",
    top_experts: "ඉහළම 5% SkilledLK විශේෂඥයින්",
    location: "ස්ථානය",
    within_5km: "කි.මී. 5ක් ඇතුළත",
    within_10km: "කි.මී. 10ක් ඇතුළත",
    within_20km: "කි.මී. 20ක් ඇතුළත",
    any_distance: "ඕනෑම දුරක්",
    recommended: "නිර්දේශිත",
    highest_rated: "ඉහළම ශ්‍රේණිගත කිරීම්",
    lowest_price: "අඩුම මිල",
    highest_price: "වැඩිම මිල",
    most_experienced: "වැඩිම පළපුරුද්ද",
    privacy_policy: "රහස්‍යතා ප්‍රතිපත්තිය",
    terms_of_service: "සේවා කොන්දේසි",
    help_center: "උදවු මධ්‍යස්ථානය",
    contact_support: "සහාය අමතන්න",
    notifications: "දැනුම්දීම්",
    mark_all_read: "සියල්ල කියවූ ලෙස ලකුණු කරන්න",
    show_less_notif: "අඩු දැනුම්දීම් පෙන්වන්න",
    see_all_notif: "සියලුම දැනුම්දීම් බලන්න",
    messages: "පණිවිඩ",
    profile: "පැතිකඩ",
    toggle_menu: "මෙනුව ක්‍රියාත්මක කරන්න/අක්‍රිය කරන්න",
    reviews_label: "සමාලෝචන",
    starting_from: "ආරම්භක මිල",
    chat_first: "පළමුව කතාබස් කරන්න",
  },
  Tamil: {
    good_morning: "காலை வணக்கம்",
    find_skilled: "இலங்கையில் சிறந்த திறமையான நிபுணர்களைக் கண்டறியவும்",
    explore_sub: "எங்கள் பரந்த அளவிலான சேவைகளை உலாவுக",
    search_hint: "உங்களுக்கு என்ன சேவை தேவை?",
    search_location: "கொழும்பு, இலங்கை",
    search: "தேடு",
    popular: "பிரபலமானவை",
    explore_categories: "வகைகளை ஆராயுங்கள்",
    view_all: "அனைத்து பிரிவுகளையும் பார்க்கவும்",
    top_rated: "உயர் மதிப்பீடு பெற்ற வல்லுநர்கள்",
    book_now: "இப்போதே பதிவு செய்யுங்கள்",
    view_profile: "சுயவிவரம் பார்க்க",
    home: "முகப்பு",
    search_nav: "தேடல்",
    bookings: "பதிவுகள்",
    verified: "சரிபார்க்கப்பட்டது",
    unverified: "சரிபார்க்கப்படாத ஊழியர்",
    featured: "சிறப்பு",
    starting_at: "இருந்து தொடங்குகிறது",
    rate_review: "மதிப்பிட்டு கருத்துரைக்கவும்",
    feedback_given: "கருத்து வழங்கப்பட்டது",
    about: "பற்றி",
    filters: "வடிகட்டிகள்",
    refine_search: "உங்கள் தேடலைச் சுருக்கவும்",
    price_range: "விலை வரம்பு",
    under_5000: "LKR 5,000 க்கும் கீழ்",
    between_5000_15000: "LKR 5,000 - 15,000",
    ratings: "மதிப்பீடுகள்",
    distance: "தூரம்",
    verified_status: "சரிபார்க்கப்பட்ட நிலை",
    verified_only: "சரிபார்க்கப்பட்ட ஊழியர்கள் மட்டும்",
    categories: "வகைகள்",
    clear_all_filters: "அனைத்து வடிப்பான்களையும் நீக்கு",
    showing: "காண்பிக்கிறது",
    professionals: "வல்லுநர்கள்",
    in: "இல்",
    no_professionals: "தொழில்முறை வல்லுநர்கள் யாரும் காணப்படவில்லை",
    no_professionals_sub: "உங்கள் தேடல், வடிப்பான்கள், வகை அல்லது தூரத்தை மாற்றி முயற்சிக்கவும்.",
    sort_by: "வரிசைப்படுத்து",
    pro_member: "சார்பு உறுப்பினர்",
    top_experts: "சிறந்த 5% SkilledLK நிபுணர்கள்",
    location: "இடம்",
    within_5km: "5 கிமீக்குள்",
    within_10km: "10 கிமீக்குள்",
    within_20km: "20 கிமீக்குள்",
    any_distance: "எந்த தூரமும்",
    recommended: "பரிந்துரைக்கப்பட்டது",
    highest_rated: "உயர் மதிப்பீடு",
    lowest_price: "குறைந்த விலை",
    highest_price: "அதிக விலை",
    most_experienced: "அதிக அனுபவம்",
    privacy_policy: "தனியுரிமைக் கொள்கை",
    terms_of_service: "சேவை விதிமுறைகள்",
    help_center: "உதவி மையம்",
    contact_support: "ஆதரவைத் தொடர்பு கொள்ளவும்",
    notifications: "அறிவிப்புகள்",
    mark_all_read: "அனைத்தையும் படித்ததாகக் குறிக்கவும்",
    show_less_notif: "குறைவான அறிவிப்புகளைக் காட்டு",
    see_all_notif: "அனைத்து அறிவிப்புகளையும் காண்க",
    messages: "செய்திகள்",
    profile: "சுயவிவரம்",
    toggle_menu: "மெனுவை மாற்று",
    reviews_label: "மதிப்புரைகள்",
    starting_from: "தொடக்க விலை",
    chat_first: "முதலில் அரட்டையடிக்கவும்",
  }
};

export function getTranslation(lang = 'English') {
  return translations[lang] || translations.English;
}
